### PR TITLE
Platform fixes

### LINKED ISSUE #134: Rework Gapfiller

### PR DESCRIPTION
**Pull request by marcelhollerbach**
this fixes #134

### CODE REVIEW

File: src/main/java/edu/kit/ipd/crowdcontrol/objectservice/crowdworking/PlatformManager.java [hunk 1]
```diff
@@ -126,12 +127,11 @@ public Payment getPlatformPayment(String name) {
      *
      * @param name The name of the platform
      * @param experiment The experiment to publish
-     * @return None if the platform does not exist
+     * @throws IllegalStateException if this gets thrown the experiment is not published.
```
Comment (TheRittler) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/crowdworking/PlatformManager.java]: shouldn't this be a PreActionException?

File: src/main/java/edu/kit/ipd/crowdcontrol/objectservice/crowdworking/PreActionException.java [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+ */
+public class PreActionException extends Exception {
+
+    /**
+     * Create a new exception to indicate that a desired action could not take place.
+     *
+     * @param exception The reason why a action could not take place
+     */
+    public PreActionException(Exception exception) {
+        super("A exception happends before the action took place", exception);
```
Comment (TheRittler) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/crowdworking/PreActionException.java]: *happend

File: src/main/java/edu/kit/ipd/crowdcontrol/objectservice/rest/resources/ExperimentResource.java [hunk 3]
```diff
@@ -110,10 +109,10 @@ public void endExperiment(Experiment experiment) {
...
             try {
                 platformManager.unpublishTask(population.getPlatformId(), experiment).join();
-            } catch (TaskOperationException e) {
-                log.fatal("Fatal ERROR! Cannot unpublish!" + e.getMessage());
-            } catch (Exception e) {
-                log.fatal("Fatal Error! Was not able to unpublish experiment" + e.getMessage());
+            } catch (PreActionException e) {
+                log.fatal("Failed to publish experiment "+experiment+" on platform "+population.getPlatformId(), e.getCause());
+            } catch (CompletionException e) {
+                log.fatal("publish failed, cause by "+e);
```
Comment (TheRittler) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/rest/resources/ExperimentResource.java]: I would prefer error messages with unified format.

Comment (LeanderK) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/rest/resources/ExperimentResource.java]: its, `, e)`, not `e.getCause()` or `+e`

File: src/main/java/edu/kit/ipd/crowdcontrol/objectservice/crowdworking/PlatformManager.java [hunk 4]
```diff
@@ -178,45 +179,42 @@ public Payment getPlatformPayment(String name) {
...
+                    return success;
+                });
     }
 
     /**
-     * update the given experiment on the given platform
-     * @param name The name of the platform
-     * @param experiment The experiment to update
-     * @return None if the platform was not found, false if the update failed and true if everything went fine.
+     * Get teh experimentsPlatformRecord or throw a preaction exception
```
Comment (simonkorz) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/crowdworking/PlatformManager.java]: typo

File: src/main/java/edu/kit/ipd/crowdcontrol/objectservice/payment/PaymentDispatcher.java [hunk 5]
```diff
@@ -64,9 +61,9 @@ private void dispatchPayment(Experiment exp) {
                 .forEach((platform, paymentJobs) -> {
                     try {
                         platformManager.payExperiment(platform, exp, paymentJobs);
-                    } catch (TaskOperationException | IllegalWorkerSetException e) {
-                        //TODO maybe notify researcher?
-                        log.fatal(String.format("Unable to pay workers for platform %s", platform), e);
+                        //TODO props to the guy which missed the .join          ^^^^^^^^
+                    } catch (PreActionException e) {
+                        log.fatal("Payment of experiment "+exp+" on platform "+platform+" could not take place!", e.getCause());
```
Comment (simonkorz) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/payment/PaymentDispatcher.java:66]: Should probably be `, e)` instead of `,e.getCause())`

Comment (marcelhollerbach) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/payment/PaymentDispatcher.java:66]: No, since the log message already tells you that the action could not take place, so we want to see the cause, not that is could not take place again.

Comment (simonkorz) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/payment/PaymentDispatcher.java:66]: this came to my mind the moment after I wrote the comment, but I don't understand the difference to [this occurence](https://github.com/coolcrowd/object-service/pull/167/files#diff-2425f803cafeeac399221651ee67d14bR86)

Comment (marcelhollerbach) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/payment/PaymentDispatcher.java:66]: Below both cases are covered, completed and none completed, here the catch clause definitely happens when the problem occurred before a action happend
