### PR TITLE
notification: improved error message

### LINKED ISSUE #260: Notification Failure
```
10:46:41.500 [pool-5-thread-1] ERROR edu.kit.ipd.crowdcontrol.objectservice.notification.Notification - An exception occurred while checking or sending a notification. java.lang.IllegalStateException: Duplicate key +---------------------+---------+------------+------------+
|id_notification_Token|result_id|result_token|notification|
+---------------------+---------+------------+------------+
|              *{null}|       *1|*???        |          *9|
+---------------------+---------+------------+------------+
at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
at java.util.HashMap.merge(HashMap.java:1245)
at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.Iterator.forEachRemaining(Iterator.java:116)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at edu.kit.ipd.crowdcontrol.objectservice.notification.SQLEmailNotificationPolicy.check(SQLEmailNotificationPolicy.java:80)
at edu.kit.ipd.crowdcontrol.objectservice.notification.SQLEmailNotificationPolicy.check(SQLEmailNotificationPolicy.java:27)
at edu.kit.ipd.crowdcontrol.objectservice.notification.NotificationPolicy.invoke(NotificationPolicy.java:25)
at edu.kit.ipd.crowdcontrol.objectservice.notification.Notification.run(Notification.java:98)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by LeanderK**
this fixes #260

### CODE REVIEW

File: src/main/java/edu/kit/ipd/crowdcontrol/objectservice/notification/SQLEmailNotificationPolicy.java [hunk 1]
```diff
@@ -71,13 +71,17 @@ private boolean recordHasIdAndTokenField(Record record) {
...
+                    try (Stream<Record> recordStream = operations.runReadOnlySQL(notification.getQuery())) {
+                        tokenRecords = recordStream.map(record -> new NotificationTokenRecord(
+                                null,
+                                record.getValue("id", Integer.class),
+                                record.getValue("token", String.class),
+                                notification.getId()))
+                                .collect(Collectors.toMap(NotificationTokenRecord::getResultId, Function.identity()));
+                    }
+                } catch (java.lang.IllegalStateException e) {
+                    throw new IllegalStateException("Invalid SQL-query, ech id has to be unique!", e);
```
Comment (kelunik) [inline src/main/java/edu/kit/ipd/crowdcontrol/objectservice/notification/SQLEmailNotificationPolicy.java:84]: I think we should sent the a mail to the specified recipients.
